import { type MuscleGroup } from '../types';

export const muscleGroups: MuscleGroup[] = [
  {
    id: 'quads',
    displayName: 'Quadriceps',
    sizeCategory: 'large',
    mevLow: 3,
    mevHigh: 6,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'MEDIUM',
  },
  {
    id: 'hamstrings',
    displayName: 'Hamstrings',
    sizeCategory: 'large',
    mevLow: 3,
    mevHigh: 6,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'LOW',
  },
  {
    id: 'glutes',
    displayName: 'Glutes',
    sizeCategory: 'large',
    mevLow: 3,
    mevHigh: 6,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'LOW',
  },
  {
    id: 'chest',
    displayName: 'Chest',
    sizeCategory: 'large',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'LOW',
  },
  {
    id: 'lats',
    displayName: 'Lats',
    sizeCategory: 'large',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'LOW',
  },
  {
    id: 'upper-back',
    displayName: 'Upper Back',
    sizeCategory: 'large',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 16,
    evidenceGrade: 'LOW',
  },
  {
    id: 'side-delts',
    displayName: 'Side Delts',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'rear-delts',
    displayName: 'Rear Delts',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'front-delts',
    displayName: 'Front Delts',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'biceps',
    displayName: 'Biceps',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 4,
    optimalHigh: 8,
    mrvLow: 10,
    mrvHigh: 14,
    evidenceGrade: 'MEDIUM',
  },
  {
    id: 'triceps',
    displayName: 'Triceps',
    sizeCategory: 'small',
    mevLow: 3,
    mevHigh: 6,
    optimalLow: 6,
    optimalHigh: 10,
    mrvLow: 10,
    mrvHigh: 14,
    evidenceGrade: 'MEDIUM',
  },
  {
    id: 'abs',
    displayName: 'Abs',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 4,
    optimalHigh: 8,
    mrvLow: 8,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'obliques',
    displayName: 'Obliques',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 4,
    optimalHigh: 8,
    mrvLow: 8,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'lower-traps',
    displayName: 'Lower Traps',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 4,
    optimalHigh: 8,
    mrvLow: 8,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
  {
    id: 'forearms',
    displayName: 'Forearms',
    sizeCategory: 'small',
    mevLow: 2,
    mevHigh: 4,
    optimalLow: 4,
    optimalHigh: 8,
    mrvLow: 8,
    mrvHigh: 14,
    evidenceGrade: 'LOW',
  },
];
