import type { DayTemplateWithSlots } from '../types';

export const HYBRID_PROGRAM_ID = 'hybrid-bb-2';
export const HYBRID_PHASE_1_ID = 'hybrid-bb-2-phase-1';
export const HYBRID_PHASE_2_ID = 'hybrid-bb-2-phase-2';
export const HYBRID_PHASE_3_ID = 'hybrid-bb-2-phase-3';

export interface SeedProgramSlot {
  slotOrder: number;
  defaultExerciseId: string;
  inputMode?: 'reps' | 'timed';
  targetSets: number;
  targetRepLow: number;
  targetRepHigh: number;
  restSeconds: number;
  notes?: string;
  alternateExerciseIds?: string[];
}

export interface SeedProgramDay {
  dayNumber: number;
  dayName: string;
  slots: SeedProgramSlot[];
}

export interface SeedProgramPhase {
  id: string;
  name: string;
  phaseOrder: number;
  days: SeedProgramDay[];
}

// ---------------------------------------------------------------------------
// Phase 1 (B.2.1)
// "Phase 1 features lower volumes across the board. Push your sets hard to
// ensure you're getting the most out of the least!"
// ---------------------------------------------------------------------------
export const phaseOneProgramDays: SeedProgramDay[] = [
  {
    dayNumber: 1,
    dayName: 'Lower Body 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'broad-jumps',
        targetSets: 3,
        targetRepLow: 5,
        targetRepHigh: 5,
        restSeconds: 60,
        notes: 'Perform as unbroken jumps. Reset between reps.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'barbell-back-squat',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 6,
        restSeconds: 120,
        notes: '1-2 RIR. Your choice of squat position.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'lying-leg-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['seated-leg-curl'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'ghd-raise',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['hanging-knee-raise', 'hanging-leg-raise'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'hyperextension-glute',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '0-1 RIR. Glute focus.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'wall-hip-flexor-stretch',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 15,
        notes: '30s hold each side.',
      },
    ],
  },
  {
    dayNumber: 2,
    dayName: 'Chest & Biceps 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'barbell-bench-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'chest-dip',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['assisted-dips'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'cable-crucifix-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['cable-lateral-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'preacher-curl-ez',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['spider-curl', 'barbell-curl', 'dumbbell-curl'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'dead-hang-passive',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s passive hang.',
      },
    ],
  },
  {
    dayNumber: 3,
    dayName: 'Back & Triceps 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'rack-assisted-chin-up',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: 'Medium width, supinated or neutral grip. 1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'machine-row',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR. Your choice of machine.',
        alternateExerciseIds: ['seated-cable-row', 'inverted-row'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'dumbbell-y-raise',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR. Superset with C2.',
        alternateExerciseIds: ['cable-y-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'jm-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR. Superset with C1.',
        alternateExerciseIds: ['triceps-extension-cable'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'metcon-circuit',
        inputMode: 'timed',
        targetSets: 4,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '4 rounds: 1 min Box Step Overs (right) + 1 min (left), then carry 1 min.',
        alternateExerciseIds: ['box-step-overs', 'ql-walk-carry'],
      },
    ],
  },
  {
    dayNumber: 4,
    dayName: 'Lower Body 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'bss-hops',
        targetSets: 3,
        targetRepLow: 20,
        targetRepHigh: 20,
        restSeconds: 60,
        notes: '20 jumps per side. Minimal rest between sets/sides.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'bulgarian-split-squat',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR per side.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'stiff-leg-deadlift',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['single-leg-stiff-leg-deadlift'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'reverse-nordic',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['leg-extension'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'mobility-metcon',
        inputMode: 'timed',
        targetSets: 5,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 30,
        notes: '5 rounds of: 10 reps Twisting Bear + carry circuit.',
      },
    ],
  },
  {
    dayNumber: 5,
    dayName: 'Chest & Biceps 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'db-incline-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'cable-crossover',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'side-lying-compound-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR per side. Superset with C2.',
        alternateExerciseIds: ['side-lying-lateral-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'dumbbell-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR per side. Superset with C1.',
        alternateExerciseIds: ['spider-curl'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'lying-cable-curl-pronated',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '0-1 RIR. Pronated grip.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'dead-hang-passive',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s passive hang.',
      },
    ],
  },
  {
    dayNumber: 6,
    dayName: 'Back & Triceps 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'lat-pulldown',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'inverted-row',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 75,
        notes: '1-2 RIR. Upper back focus.',
        alternateExerciseIds: ['machine-row'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'rear-delt-fly',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR. Cable rear delt fly.',
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'triceps-extension-cable',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR. Cable cross triceps extension.',
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'hill-sprints',
        inputMode: 'timed',
        targetSets: 6,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s on / 60s walk-light jog. Comfortable pace.',
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Phase 2 (B.2.2)
// "Phase 2 follows a similar structure to phase 1, adding in some small
// variations to accessories and metcons to keep things progressing on the
// main movements."
// ---------------------------------------------------------------------------
export const phaseTwoProgramDays: SeedProgramDay[] = [
  {
    dayNumber: 1,
    dayName: 'Lower Body 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'broad-jumps',
        targetSets: 3,
        targetRepLow: 5,
        targetRepHigh: 5,
        restSeconds: 60,
        notes: 'Perform as unbroken jumps.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'barbell-back-squat',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 6,
        restSeconds: 120,
        notes: '1-2 RIR. Your choice of squat position.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'seated-leg-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['lying-leg-curl'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'ghd-raise',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['hanging-knee-raise'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'hyperextension-glute',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '0-1 RIR. Glute focus.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'horse-stance-hold',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 15,
        notes: '30s hold per round.',
      },
    ],
  },
  {
    dayNumber: 2,
    dayName: 'Chest & Biceps 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'barbell-bench-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'chest-dip',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['assisted-dips'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'overhead-lateral-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['cable-lateral-raise', 'side-lying-lateral-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'preacher-curl-ez',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['spider-curl', 'barbell-curl'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'dead-hang-passive',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s passive hang.',
      },
    ],
  },
  {
    dayNumber: 3,
    dayName: 'Back & Triceps 1',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'rack-assisted-chin-up',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: 'Medium width, supinated or neutral grip. 1-2 RIR.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'seated-cable-row',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['machine-row'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'cable-y-raise',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR. Superset with C2.',
        alternateExerciseIds: ['dumbbell-y-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'triceps-pushdown',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR. Superset with C1.',
        alternateExerciseIds: ['triceps-extension-cable'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'metcon-circuit',
        inputMode: 'timed',
        targetSets: 1,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: 'AMRAP in 10 minutes.',
        alternateExerciseIds: ['box-step-overs', 'ql-walk-carry'],
      },
    ],
  },
  {
    dayNumber: 4,
    dayName: 'Lower Body 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'bss-hops',
        targetSets: 3,
        targetRepLow: 20,
        targetRepHigh: 20,
        restSeconds: 60,
        notes: '20 jumps per side.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'bulgarian-split-squat',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR per side.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'stiff-leg-deadlift',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['single-leg-stiff-leg-deadlift'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'sissy-squat',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['leg-extension'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'sled-push',
        inputMode: 'timed',
        targetSets: 5,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s on / 60s off. Not all-out — sustainable pace.',
        alternateExerciseIds: ['mobility-metcon'],
      },
    ],
  },
  {
    dayNumber: 5,
    dayName: 'Chest & Biceps 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'smith-machine-incline-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['db-incline-press'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'incline-dumbbell-fly',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['cable-crossover'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'side-lying-compound-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR per side. Superset with C2.',
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'zottman-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR per side. Superset with C1.',
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'incline-hammer-curl',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'dead-hang-passive',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s passive hang.',
      },
    ],
  },
  {
    dayNumber: 6,
    dayName: 'Back & Triceps 2',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'single-arm-lat-pulldown',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['lat-pulldown'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'inverted-row',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 75,
        notes: '1-2 RIR. Upper back focus.',
        alternateExerciseIds: ['machine-row'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'dumbbell-rear-delt-fly',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['rear-delt-fly'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'incline-skullcrusher',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['triceps-extension-cable'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'hill-sprints',
        inputMode: 'timed',
        targetSets: 6,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 120,
        notes: '60s on / 120s walk-light jog. Sustainable pace.',
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Phase 3 (B.2.3)
// "Phase 3 blends more power & strength into your workouts, whilst keeping
// in a similar theme to the first 2 phases. This phase runs for just 4 weeks
// to prevent too much fatigue accumulating by the end of the block."
// ---------------------------------------------------------------------------
export const phaseThreeProgramDays: SeedProgramDay[] = [
  {
    dayNumber: 1,
    dayName: 'Power Legs',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'rocker-broad-jump',
        targetSets: 3,
        targetRepLow: 5,
        targetRepHigh: 5,
        restSeconds: 20,
        notes: 'Reset between reps. 20s rest between sets.',
        alternateExerciseIds: ['broad-jumps'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'barbell-back-squat',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 10,
        restSeconds: 150,
        notes: '1 top set 3-5 reps + 1 backdown 6-10 reps.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'single-leg-lying-leg-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '0-1 RIR per side.',
        alternateExerciseIds: ['lying-leg-curl', 'seated-leg-curl'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'hanging-leg-raise',
        targetSets: 3,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['hanging-knee-raise', 'ghd-raise'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'dual-elevated-hip-thrust',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 75,
        notes: '0-1 RIR per side.',
        alternateExerciseIds: ['hyperextension-glute'],
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'horse-stance-hold',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 15,
        notes: '30s hold per round.',
      },
    ],
  },
  {
    dayNumber: 2,
    dayName: 'Power Push',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'barbell-overhead-press',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 10,
        restSeconds: 150,
        notes: '1 top set 3-5 reps + 1 backdown 6-10 reps.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'barbell-bench-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'incline-trap-3-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['cable-y-raise', 'dumbbell-y-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'dumbbell-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '0-1 RIR.',
        alternateExerciseIds: ['preacher-curl-ez', 'spider-curl'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'dead-hang-passive',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '60s passive hang.',
      },
    ],
  },
  {
    dayNumber: 3,
    dayName: 'Power Pull',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'rack-assisted-chin-up',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 10,
        restSeconds: 150,
        notes: 'Medium width. 1 top set 3-5 + 1 backdown 6-10.',
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'pendlay-row',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['machine-row', 'seated-cable-row'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'dumbbell-lateral-raise',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR. Superset with C2.',
        alternateExerciseIds: ['cable-lateral-raise', 'overhead-lateral-raise'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'triceps-overhead-extension',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR. Superset with C1.',
        alternateExerciseIds: ['triceps-extension-cable', 'triceps-pushdown'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'single-db-muscle-snatch',
        targetSets: 3,
        targetRepLow: 15,
        targetRepHigh: 15,
        restSeconds: 30,
        notes: '15 per side. Switch starting side each round. Superset with D2.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'feet-elevated-shoulder-taps',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 30,
        notes: '40s per round, then rest before returning to D1.',
      },
    ],
  },
  {
    dayNumber: 4,
    dayName: 'Posterior Chain',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'stiff-leg-deadlift',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 120,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['single-leg-stiff-leg-deadlift'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'bulgarian-split-squat',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR per side.',
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'cable-glute-kickback',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR per side. Superset with C2.',
        alternateExerciseIds: ['hyperextension-glute'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'copenhagen-plank',
        inputMode: 'timed',
        targetSets: 2,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 30,
        notes: '30s per side. Superset with C1.',
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'leg-extension',
        targetSets: 2,
        targetRepLow: 8,
        targetRepHigh: 12,
        restSeconds: 75,
        notes: '0-1 RIR.',
        alternateExerciseIds: ['reverse-nordic', 'sissy-squat'],
      },
    ],
  },
  {
    dayNumber: 5,
    dayName: 'Chest & Biceps',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'smith-machine-incline-press',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 10,
        restSeconds: 150,
        notes: '1 top set 3-5 + 1 backdown 6-10.',
        alternateExerciseIds: ['db-incline-press', 'barbell-bench-press'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'cable-chest-press',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['cable-crossover'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'cable-crucifix-raise',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: '1-2 RIR. Superset with C2.',
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'cable-curl',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 60,
        notes: '1-2 RIR. Superset with C1.',
        alternateExerciseIds: ['preacher-curl-ez', 'dumbbell-curl'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'spider-curl',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: 'Push both sets to complete partial range failure.',
      },
      {
        slotOrder: 6,
        defaultExerciseId: 'single-arm-eagle-grip-hang',
        inputMode: 'timed',
        targetSets: 3,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 60,
        notes: '30s per side.',
        alternateExerciseIds: ['dead-hang-passive'],
      },
    ],
  },
  {
    dayNumber: 6,
    dayName: 'Back, Triceps & Sprints',
    slots: [
      {
        slotOrder: 1,
        defaultExerciseId: 'machine-row',
        targetSets: 2,
        targetRepLow: 3,
        targetRepHigh: 10,
        restSeconds: 150,
        notes: 'Upper back focus. 1 top set 3-5 + 1 backdown 6-10.',
        alternateExerciseIds: ['pendlay-row', 'seated-cable-row'],
      },
      {
        slotOrder: 2,
        defaultExerciseId: 'single-arm-lat-pulldown',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 90,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['lat-pulldown'],
      },
      {
        slotOrder: 3,
        defaultExerciseId: 'rear-delt-fly',
        targetSets: 2,
        targetRepLow: 10,
        targetRepHigh: 15,
        restSeconds: 60,
        notes: 'Take both sets to complete partial range.',
        alternateExerciseIds: ['dumbbell-rear-delt-fly'],
      },
      {
        slotOrder: 4,
        defaultExerciseId: 'triceps-dip',
        targetSets: 2,
        targetRepLow: 6,
        targetRepHigh: 10,
        restSeconds: 75,
        notes: '1-2 RIR.',
        alternateExerciseIds: ['chest-dip', 'assisted-dips'],
      },
      {
        slotOrder: 5,
        defaultExerciseId: 'hill-sprints',
        inputMode: 'timed',
        targetSets: 5,
        targetRepLow: 1,
        targetRepHigh: 1,
        restSeconds: 180,
        notes: '60s on / 180s walk-light jog.',
      },
    ],
  },
];

export const seedProgramPhases: SeedProgramPhase[] = [
  {
    id: HYBRID_PHASE_1_ID,
    name: 'Phase 1',
    phaseOrder: 1,
    days: phaseOneProgramDays,
  },
  {
    id: HYBRID_PHASE_2_ID,
    name: 'Phase 2',
    phaseOrder: 2,
    days: phaseTwoProgramDays,
  },
  {
    id: HYBRID_PHASE_3_ID,
    name: 'Phase 3',
    phaseOrder: 3,
    days: phaseThreeProgramDays,
  },
];

export const placeholderDayTemplate: DayTemplateWithSlots = {
  id: -1,
  phaseId: HYBRID_PHASE_1_ID,
  dayNumber: 1,
  dayName: 'Lower Body 1',
  slots: [],
};
